package domainmodel;
// Generated Feb 22, 2018 5:18:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private Integer noteid;
     private Date dateCreated;
     private String contents;

    public Note() {
    }

	
    public Note(String contents) {
        this.contents = contents;
    }
    public Note(Integer noteid, Date dateCreated, String contents) {
       this.noteid = noteid;
       this.dateCreated = dateCreated;
       this.contents = contents;
    }
   
    public Integer getNoteid() {
        return this.noteid;
    }
    
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }




}


